import { recommendationSourceRegistry } from "../providers/sourceRegistry";
import { RecommendationConfig } from "../types";

const HOUR_MS = 60 * 60 * 1000;
const DAY_MS = 24 * HOUR_MS;

export const defaultRecommendationConfig: RecommendationConfig = {
  canonicalization: {
    strictMergeThreshold: 5.5,
    relaxedMergeThreshold: 4.5,
    maxDurationDeltaMsStrict: 4000,
    maxDurationDeltaMsRelaxed: 7000,
    titleExactBoost: 2.5,
    artistExactBoost: 2,
    mbRecordingMatchBoost: 12,
    acoustIdMatchBoost: 10,
    titleFlavorConflictPenalty: 6,
    artistMismatchPenalty: 2.5,
    durationMismatchPenalty: 2,
    blockOnFlavorConflict: true,
    blockOnConflictingMbRecordingIds: true,
    blockOnPrimaryArtistConflict: true,
    enableTrackCanonicalization: true,
    enableAggressiveDedup: false,
    enableFingerprintFallback: false,
    lyricsDurationBucketMs: 2000,
    minCanonicalConfidenceForLyricsReuse: 0.7,
    sourcePriorityByProvider: {
      musicbrainz: 100,
      acoustid: 95,
      discogs: 80,
      lastfm: 70,
      listenbrainz: 60,
      soundcloud: 50,
      jamendo: 48,
      wikidata: 45,
      lmusic: 35,
      hitmo: 34,
      hitmos: 34,
      telegram: 10,
    },
    sourceTrustByProvider: {
      musicbrainz: 1,
      acoustid: 1,
      discogs: 0.9,
      lastfm: 0.75,
      listenbrainz: 0.75,
      soundcloud: 0.55,
      jamendo: 0.6,
      wikidata: 0.6,
      lmusic: 0.35,
      hitmo: 0.35,
      hitmos: 0.35,
      telegram: 0.45,
    },
  },
  providers: recommendationSourceRegistry,
  candidatePoolSizes: {
    sameArtist: 30,
    frequentCollaborators: 30,
    relatedArtists: 40,
    sharedTags: 50,
    releaseEraProximity: 25,
    sessionContinuation: 40,
    userAffinityRetrieval: 50,
    userTopArtists: 60,
    userTopTags: 60,
    userTopTracks: 40,
    playlistCooccurrence: 60,
    sessionTransitions: 40,
    searchIntent: 30,
    adjacentDiscovery: 40,
    safeExploration: 30,
  },
  scoringWeights: {
    sameArtist: 2.4,
    collaborator: 2.2,
    relatedArtist: 1.9,
    tagOverlap: 1.8,
    sessionFit: 1.6,
    releaseProximity: 1.0,
    tasteAffinity: 1.5,
    durationFit: 0.35,
    flavorFit: 0.8,
    quality: 0.7,
    availability: 4.0,
    popularityPrior: 0.25,
    novelty: 0.4,
    repetitionPenalty: 1.4,
    duplicatePenalty: 2.5,
    skipPenalty: 2.0,
    explicitMismatchPenalty: 2.2,
  },
  userCentricBlend: {
    userAffinity: 0.45,
    recentIntent: 0.2,
    cooccurrence: 0.15,
    currentTrackContext: 0.1,
    qualityAvailability: 0.05,
    noveltyExploration: 0.05,
    currentTrackContextMaxShare: 0.25,
  },
  completionThresholds: {
    strongNegative: 0.15,
    negative: 0.4,
    neutral: 0.6,
    moderatePositive: 0.8,
    strongPositive: 0.8,
    veryStrongPositive: 0.95,
  },
  coldStart: {
    weakHistoryTrackCount: 5,
  },
  decay: {
    sessionHalfLifeMs: 6 * HOUR_MS,
    shortTermHalfLifeMs: 14 * DAY_MS,
    longTermHalfLifeMs: 45 * DAY_MS,
    playlistHalfLifeMs: 60 * DAY_MS,
    favoriteHalfLifeMs: 180 * DAY_MS,
    dislikeHalfLifeMs: 120 * DAY_MS,
  },
  exposure: {
    fatigueWindowMs: 7 * DAY_MS,
    fatiguePenaltyThreshold: 3,
    hardHideThreshold: 5,
  },
  experiments: {
    explorationQuota: 0.12,
    cooldownStrength: 1,
    resurfacingPolicy: "balanced",
  },
  filtering: {
    minCanonicalConfidence: 0.55,
  },
  diversification: {
    artistCooldownWindow: 10,
    sameArtistStreak: 3,
    sameReleaseStreak: 4,
    sameNarrowTagClusterStreak: 4,
    repeatedFeaturedArtistLoopThreshold: 3,
    maxPenaltyShare: 0.35,
  },
  autoplay: {
    sessionCentroidWindowSize: 5,
  },
};
