ALTER TYPE "TrackIndexStatus" ADD VALUE IF NOT EXISTS 'RAW';
ALTER TYPE "TrackIndexStatus" ADD VALUE IF NOT EXISTS 'CANDIDATE';
ALTER TYPE "TrackIndexStatus" ADD VALUE IF NOT EXISTS 'TRUSTED';
ALTER TYPE "TrackIndexStatus" ADD VALUE IF NOT EXISTS 'BLOCKED';

ALTER TYPE "RecommendationEventType" ADD VALUE IF NOT EXISTS 'PLAY';
ALTER TYPE "RecommendationEventType" ADD VALUE IF NOT EXISTS 'SKIP';
ALTER TYPE "RecommendationEventType" ADD VALUE IF NOT EXISTS 'SEEK';
ALTER TYPE "RecommendationEventType" ADD VALUE IF NOT EXISTS 'LIKE';
ALTER TYPE "RecommendationEventType" ADD VALUE IF NOT EXISTS 'SAVE';
ALTER TYPE "RecommendationEventType" ADD VALUE IF NOT EXISTS 'ADD_TO_PLAYLIST';
ALTER TYPE "RecommendationEventType" ADD VALUE IF NOT EXISTS 'SHARE';

ALTER TABLE "CanonicalTrack"
ADD COLUMN IF NOT EXISTS "lastIndexedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastProviderCheckAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastSeenAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "metadataFreshness" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "playableSourceFreshness" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "TrackSource"
ADD COLUMN IF NOT EXISTS "lastIndexedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastProviderCheckAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastSeenAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "metadataFreshness" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "playableSourceFreshness" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Artist"
ADD COLUMN IF NOT EXISTS "lastIndexedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastProviderCheckAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastSeenAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "metadataFreshness" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "ArtistSource"
ADD COLUMN IF NOT EXISTS "lastIndexedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastProviderCheckAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastSeenAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "metadataFreshness" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "DiscoverySeed"
ADD COLUMN IF NOT EXISTS "scope" TEXT NOT NULL DEFAULT 'user',
ADD COLUMN IF NOT EXISTS "dedupeKey" TEXT,
ADD COLUMN IF NOT EXISTS "priority" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "DiscoveryJob"
ADD COLUMN IF NOT EXISTS "dedupeKey" TEXT,
ADD COLUMN IF NOT EXISTS "rateLimitKey" TEXT;

ALTER TABLE "CanonicalTrack" ALTER COLUMN "indexStatus" SET DEFAULT 'CANDIDATE';
ALTER TABLE "TrackSource" ALTER COLUMN "indexStatus" SET DEFAULT 'CANDIDATE';

ALTER TABLE "UserRecommendationEvent"
ADD COLUMN IF NOT EXISTS "artistId" TEXT,
ADD COLUMN IF NOT EXISTS "sessionId" TEXT,
ADD COLUMN IF NOT EXISTS "sourceSurface" TEXT,
ADD COLUMN IF NOT EXISTS "position" INTEGER,
ADD COLUMN IF NOT EXISTS "occurredAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "recommendationRequestId" TEXT,
ADD COLUMN IF NOT EXISTS "context" JSONB,
ADD COLUMN IF NOT EXISTS "reasonSnapshot" JSONB,
ADD COLUMN IF NOT EXISTS "featuresSnapshot" JSONB;

CREATE UNIQUE INDEX IF NOT EXISTS "DiscoverySeed_dedupeKey_key" ON "DiscoverySeed"("dedupeKey");
CREATE INDEX IF NOT EXISTS "DiscoverySeed_scope_reason_updatedAt_idx" ON "DiscoverySeed"("scope", "reason", "updatedAt");
CREATE INDEX IF NOT EXISTS "DiscoverySeed_dedupeKey_idx" ON "DiscoverySeed"("dedupeKey");

CREATE UNIQUE INDEX IF NOT EXISTS "DiscoveryJob_dedupeKey_key" ON "DiscoveryJob"("dedupeKey");
CREATE INDEX IF NOT EXISTS "DiscoveryJob_dedupeKey_idx" ON "DiscoveryJob"("dedupeKey");
CREATE INDEX IF NOT EXISTS "DiscoveryJob_rateLimitKey_status_runAfter_idx" ON "DiscoveryJob"("rateLimitKey", "status", "runAfter");
